DROP TABLE if EXISTS restaurant cascade;

DROP TABLE IF EXISTS person;

DROP TABLE IF EXISTS reservation;

DROP TABLE IF EXISTS user_roles;

DROP TABLE IF EXISTS "role";

DROP TABLE IF EXISTS "user";

CREATE TABLE "user"
(
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25) UNIQUE NOT NULL,
    email    VARCHAR(25) UNIQUE NOT NULL,
    password VARCHAR(255)       NOT NULL
);

CREATE TABLE restaurant (
    id             INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    restaurantname VARCHAR(50)  NOT NULL,
    address        VARCHAR(250) NOT NULL,
    reservationfee INT
);

CREATE TABLE person (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    firstname VARCHAR(25)        NOT NULL,
    lastname  VARCHAR(25)        NOT NULL,
    gender    VARCHAR(10),
    age       INT DEFAULT 0,
    phone     VARCHAR(15),
    email     VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE reservation
(
    id                     INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                   VARCHAR(10) UNIQUE NOT NULL,
    quota                  INT DEFAULT 0,
    reservation_date         DATE               NOT NULL


);

CREATE TABLE "role"
(
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(10) UNIQUE NOT NULL
);

CREATE TABLE user_roles
(
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    PRIMARY KEY (user_id, role_id)
);


INSERT INTO "role" (role_name)
VALUES ('ROLE_ADMIN');
INSERT INTO "role" (role_name)
VALUES ('ROLE_USER');





INSERT INTO restaurant(restaurantname,address,reservationfee)
VALUES('Alfa','Besiktas/Istanbul // Samatya/İstanbul','50'),
      ('Beta','Bakırkoy/Istanbul','100'),
      ('Omega','Uskudar/Istanbul','75'),
      ('Shine','Kadıkoy/Istanbul','25');

INSERT INTO person(firstname,lastname,email)
VALUES ('Berk','Balci','berkbalci@gmail.com'),
       ('Mehmet','Yilmaz','mehmetyilmaz@gmail.com'),
       ('Ali','Sari','alisari@gmail.com');

INSERT INTO reservation(code,quota,reservation_date)
VALUES ('15432','5','12-11-2023'),
       ('13421','2','13-10-2024'),
       ('14122','4','14-12-2025')